In [1]:
import pandas as pd
import numpy as np

# Example

In [2]:
A = np.array([[4, 8, 6, 12]])
A.shape = (2,2)
A

array([[ 4,  8],
       [ 6, 12]])

In [3]:
B = np.array([[5, 1]])
B.shape = (2,1)
B

array([[5],
       [1]])

In [4]:
first = A.T@A
first

array([[ 52, 104],
       [104, 208]])

In [5]:
inv_first = np.linalg.pinv(first)
inv_first

array([[0.00076923, 0.00153846],
       [0.00153846, 0.00307692]])

In [6]:
# x hat
x = inv_first@A.T@B
x

array([[0.1],
       [0.2]])

In [7]:
# p is the orthogonal projection of B on the C(A)
p = A@x
p

array([[2.],
       [3.]])